---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

#dataSource:
#    logSql: true
 #   pooled: true
 #   jmxExport: true
 #   driverClassName: com.mysql.jdbc.Driver
 #   username: uniAppUser
 #   password: z*ยง7z902t34!1bpn&Z=(OT68t21&

environments:
    development:
        dataSource:
            pooled: true
            jmxExport: true
            driverClassName: com.mysql.jdbc.Driver
            username: uniAppUser
            password: z*ยง7z902t34!1bpn&Z=(OT68t21&
            dbCreate: update
            url: ''
    test:
        dataSource:
            pooled: true
            jmxExport: true
            driverClassName: com.mysql.jdbc.Driver
            username: uniAppUser
            password: z*ยง7z902t34!1bpn&Z=(OT68t21&
            dbCreate: update
            url: jdbc:mysql://localhost/uniapp
    production:
        dataSource:
            pooled: true
            jmxExport: true
            driverClassName: com.mysql.jdbc.Driver
            username: uniAppUser
            password: z*ยง7z902t34!1bpn&Z=(OT68t21&
            dbCreate: update
            url: jdbc:mysql://localhost/uniapp
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    profile: web
    codegen:
        defaultPackage: appointments
    spring:
        transactionManagement:
            proxies: false
    config:
        locations:
#            - file:///$APPOINTMENTS/config.yml
             - file:///Users/timohaffner/Workspace/Tomcat/Appointments/config.yml
             - file:///${System.getenv(env)}
#            - classpath:myconfig.groovy
#            - classpath:myconfig.yml
#            - classpath:myconfig.properties
#            - file:///etc/app/myconfig.groovy
#            - file:///etc/app/myconfig.yml
#            - file:///etc/app/myconfig.properties
#            - ~/.grails/myconfig.groovy
#            - ~/.grails/myconfig.yml
#            - ~/.grails/myconfig.properties
#            - file:${catalina.base}/myconfig.groovy
#            - file:${catalina.base}/myconfig.yml
#            - file:${catalina.base}/myconfig.properties
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mail:
        host: smtp.gmail.com
        port: 587
        username: headless705@gmail.com
        password: THaffner705
        props: [
                  "mail.smtp.auth":"true",
                  "mail.smtp.starttls.enable":"true",
                  "mail.smtp.host":"smtp.gmail.com",
                  "mail.smtp.port":"587",
                  "mail.smtp.debug":"true",
#                  "mail.smtp.socketFactory.fallback":"false"
               ]


    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

